### ISSUE TITLE
Is /announce ending mandatory?

### ISSUE THREAD

**Issue by mrx23dot** [CorralPeltzer/newTrackon#114]
Is /announce ending mandatory in tracker addresses?

In uTorrent it seems that it is only needed for non udp trackers.
Removing is would save space in magnet URLs which is limited to 2000characters.

**Comment by CorralPeltzer** [comment]
Hi! Yes, this is intentional. The path in UDP trackers is ignored by BitTorrent clients, but newTrackon adds it so they are better identified as trackers. See https://github.com/CorralPeltzer/newTrackon/issues/29#issuecomment-388585598 for further explanation.

When creating a magnet link, you can just remove the `/announce` from UDP trackers.
