### ISSUE TITLE
tace.ru trackers are weirdly showing tons of peers

### ISSUE THREAD

**Issue by txtsd** [CorralPeltzer/newTrackon#119]
Could we investigate what's going on with it?

I add `https://newtrackon.com/api/70` automatically to all my torrents which naturally pulls in the `*.tace.ru` trackers, and these trackers tend to show a lot more peers than other trackers (>100+) for no gains in speed or availability of the torrent.

**Comment by txtsd** [comment]
Look at this nonsense. Please blacklist `*.tace.ru`

![2021-01-10-152219_1253x859_scrot](https://user-images.githubusercontent.com/768728/104119788-0f120a00-5358-11eb-8658-b05c4cd5f0a3.png)

**Comment by CorralPeltzer** [comment]
Hi! Thanks for the heads up. I've observed this myself, but as you can see from https://newtrackon.com/raw, these trackers are returning normal announce responses to the random hashes newTrackon requests. This seems to happen only with some popular hashes.

Not knowing whether this is intentional or not, I'm hesitant to start blacklisting certain domains. Domains are cheap, and I'm not willing to start a cat-and-mouse game of constantly monitoring and blacklisting domains.

**Comment by txtsd** [comment]
That's fair.
