### ISSUE TITLE
UDP Tracker showing as offline but actually working

### ISSUE THREAD

**Issue by TKNLG** [CorralPeltzer/newTrackon#230]
Hey,

I added my tracker which (is supposed to be) works with http and udp, but it seems that NTO only manages to check it via http successfully. After trying to use it with an own, freshly created torrent and disabling DHT in my torrent client and only adding my tracker to its list, my tracker seems to work without any problems. Been seeing this issue since a few month already now, added my tracker in January for the first time and didnt had any problems, besides a little less uptime that it actually had, but I supposed thats due to NTO only checking once via udp and the package just getting lost here and then.

I also set up the latest NTO docker image on a server, also hostet by hetzner in NBG and it doesnt have any problems with my tracker, testing it via http and udp alike.

Tracker urls:
udp://tracker.qu.ax:6969/announce
http://tracker.qu.ax:6969/announce

Software: Opentracker

**Comment by udbnt** [comment]
same issue here, so bump

**Comment by lirener** [comment]
Test results（测试结果）：
ipv4 is work（工作）for tcp
ipv6 is  no work（不工作）for all
![test tracker](https://github.com/CorralPeltzer/newTrackon/assets/19354130/3c8f2c7e-c1d1-4836-85cf-0921cc97dc6c)
测试的BT软件：Tixati v3.19（BT software tested: Tixati v3.19）

``````````````````````````

我最近也很困惑 为什么我的tracker一直在运行 除了周末考虑休息外 从昨天开始 我就把tracker搭建在路由器上 但是我看到官网检测的结果 我离线10多小时了 我可能迫切的需要 和你们之间的及时通信 测试tracker相关信息 我从stast列表查看到 我的tracker是有用户的 不知道是不是我国墙的原因 但是想想也不应该 不知道为什么 所以 有人能帮我测试 我的tracker是否工作吗？udp://bt.rer.lol:6969/announce
I've been confused lately as to why my tracker has been running Except for the weekends when I consider taking a break Since yesterday I've built the tracker on the router But I see the results of the official website detection I've been offline for more than 10 hours I may urgently need Timely communication with you Test tracker information I looked at it from the stst list My tracker has users I don't know if it's the reason for my country's wall But I shouldn't think about it I don't know why So Can someone help me test if my tracker is working? udp://bt.rer.lol:6969/announce

``````````````````````````

能够考虑搭建一个及时聊天平台 方便我们的跨国实时通信交流 我推荐一个应用：Discord
是否能为我们创办一个群组？

I would like to consider building a real-time chat platform to facilitate our cross-border real-time communication, and I recommend one app: Discord
Can you start a group for us?

**Comment by 1265578519** [comment]
https://github.com/CorralPeltzer/newTrackon/issues/278
问题副本

`````````分割````````
qbittorrent、libtorrent和其它一些开源的BT客户端不遵守bep协议规范，请不要在tracker域名dns上解析多个ip地址
https://github.com/qbittorrent/qBittorrent/issues/20882

bep15协议地址
https://www.bittorrent.org/beps/bep_0015.html

这些客户端都没有遵守协议去判断transaction ID，如果客户端请求域名IP地址A，但是tracker通过IP地址B发生回应，那么就会导致客户端请求失败，报错skipping tracker announce （unreachable）
ipv4和ipv6都会发生这个现象，3年前和客户端作者反馈过，但是他们至今没有解决这个问题

我们作为tracker提供管理者，为了避免这个现象，请使用不同的二级域名来分配更多服务器ip，例如tracker1、tracker2、tracker3、tracker4，确保每个域名只负责一个ip地址，而且不要把多个ip地址绑定到一台相同的服务器中（极其重要）
`````````分割````````


你当前运行的opentracker 2026-04-13版本太新，有 `iob_reset` 内存空指针崩溃的风险，我和开发者正在修复这个问题，如果遇到崩溃建议回退到2024-05-10版本
请使用2024-05-10的提交代码，这是一个经过我验证的稳定版，或者在网站下载完整包 opentracker-1.0.tar.bz2
https://erdgeist.org/gitweb/opentracker/commit/?id=59c1c30107ccba4c633ae7ca11c3249c88719e83
https://github.com/1265578519/OpenTracker

如果你使用了docker，可以考虑我制作的容器镜像
https://hub.docker.com/r/1265578519/opentracker
