### ISSUE TITLE
No bug but decision?

### ISSUE THREAD

**Issue by numb3rs666** [CorralPeltzer/newTrackon#29]
Hi, I have tried to submit a link like http://website.com:80/tracker/announce.php.
The result is http://website.com:80/announce Error 404 the sub directory (/tracker) and file extension (.php) was removed.
Could I ask the reason?

Thanks a lot

**Comment by CorralPeltzer** [comment]
Hi! Yes, this is on purpose. While I know that HTTP(S) trackers can answer on other directories than `/announce` and that UDP trackers don't even need any path because paths don't exist in the UDP tracker protocol, I think it is a good practice to make trackers available in the `/announce` path. It is basically an standard in trackers nowadays and helps identify easily the URL that users should add to their BitTorrent clients. That is why I _standardize_ all request to that path, and even add it to UDP trackers URLs. I recommend you to make your tracker available from that path.
