### ISSUE TITLE
Request: Idea’s For Website

### ISSUE THREAD

**Issue by zero77** [CorralPeltzer/newTrackon#3]
hello, can you display all working duplicate trackers in the list under the main tracker URL. Because this will make it quicker and easier when submitting trackers to see if the tracker is already been added instead of having to manually resolve the IP to see if it is a duplicate. 

Additionally, if the main tracker is down can you also check the duplicate trackers, to see for some reason if one of the duplicates is working when the main one is not, and then use that instead. 

Also, can you please show the results in the submitted tab after you have submitted new trackers so it is possible to see why the trackers weren’t added.

Thanks

**Comment by CorralPeltzer** [comment]
Thanks for the ideas!

If with "duplicate trackers" you mean trackers with different hostname or port but resolving to the same IPs, I don't think that's possible. Lots of DNS servers resolve to the same IPs to any subdomain queried, for example, a.tracker.com, b.tracker.com and c.tracker.com would be valid duplicate trackers if the DNS server of tracker.com is configured like that. Furthermore, with services like [afraid.org](https://freedns.afraid.org/) anyone can have unlimited subdomains for free. Because of the collaborative feature of the site, this would lead to being able to submit an infinite number of duplicate trackers.

About the results of trackers submission, I'm implementing it, will have it soon.

**Comment by zero77** [comment]
Excellent thank you, yes sorry I didn’t specify, I mean a combination of different things including subdomains also different ports with the same domain and protocols like http/https and udp. 

Also, different domains like RARBG use for instance they have rarbg.to or .me or .com and also I don’t know if it makes any difference but also when trackers end with /announce
