### ISSUE TITLE
[Request] Showing Test Settings

### ISSUE THREAD

**Issue by zero77** [CorralPeltzer/newTrackon#6]
Can you please show the settings and parameters you are using to test the trackers on the submitted page.

Also, a large amount of trackers appear to be timing out although, I have successfully used some of them within a torrent client, do some of the settings need adjusting particularly time out.
Thanks

**Comment by CorralPeltzer** [comment]
The trackers are tested with an announce request with a random hash, I tried to follow BEPs [3](http://www.bittorrent.org/beps/bep_0003.html) and [15](http://www.bittorrent.org/beps/bep_0015.html), but there are probably some bugs in my implementation. An example request can be "http<span></span>://tracker.com:80/announce?info_hash=NmQE%A2%E7%B3%3C%FF%3E%9F%18%17%16hnJ%A5j%F6&peer_id=-qB3360-vrasg7LC0OXJ&port=6881&uploaded=0&downloaded=0&left=0&compact=1"

I don't think timeout is the problem, it is 10 seconds for both UDP and HTTP. Could you list the trackers that work for you but don't get accepted in by the site, so I can try to fix the problem? Remember that only trackers that accept any hash are open, for example, udp://tracker.trackerfix.com:80/announce is a popular one but it only tracks torrents from RARBG, AFAIK.

**Comment by zero77** [comment]
when I next come across a tracker that works for me and is not working when tested I will post it.

Also, do you think it would help to test a few different random hashes from a few different sites. 

So trackers that only work with specific sites don’t fail, or allowing the users to provide a hash that the tracker could be tested against alongside the random hash/hashes.

There may also be a bug that is stopping the accepted trackers being posted to the list.

**Comment by kxmp** [comment]
@CorralPeltzer
Hey, I can't add this tracker udp://tracker.pirateparty.gr:6969/announce
Is that blacklisted or bug?

**Comment by CorralPeltzer** [comment]
@kxmp 
[tracker.pirateparty.gr](http://tracker.pirateparty.gr/) resolves to 62.138.0.158, the same IP as a bigger and more known tracker, [tracker.coppersurfer.tk](http://tracker.coppersurfer.tk/). I suppose they have some sort of agreement since coppersurfer.tk recommends pirateparty.gr, but because newTrackon only allows different IPs, they cannot be both on the list.

About zer0day, thanks a lot for reporting, the nreTrackon server had Google public DNS resolvers configured and it seems [they are not resolving that name](https://dns.google.com/query?name=tracker.zer0day.to&type=ANY&dnssec=false), I have already changed the DNS resolvers to [DNS.WATCH](https://dns.watch/) and it is working again.

**Comment by zero77** [comment]
> About zer0day, thanks a lot for reporting, the nreTrackon server had Google public DNS resolvers configured and it seems they are not resolving that name, I have already changed the DNS resolvers to DNS.WATCH and it is working again.

It may be worth using a secondary DNS server for redundancy and in case the first server fails to resolve the domain.

There’s a good list hear, github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

**Comment by CorralPeltzer** [comment]
I have added a few, thanks for the tip!
