### ISSUE TITLE
please add a new API to return trackers by status

### ISSUE THREAD

**Issue by sandrotosi** [CorralPeltzer/newTrackon#65]
Hello,
it would be helpful to have a new API endpoint, listing the trackers in order of their status

at the top, the trackers with status working, ordered by the longest working at the top, descending; at the bottom, the trackers with status down

**Comment by CorralPeltzer** [comment]
Hi! If you mean to order the list of trackers by uptime, that is already being done. All API endpoints return the trackers in the same order as the main table, which is first by uptime, and then by time from being added.

If you mean ordering trackers by the last time they failed or answered a request (Status column), I don't think that's a valuable metric to order trackers. Two different trackers with both 99.9% of uptime but one having failed a request a week ago and the other three weeks ago, should be considered equally stable. The time displayed by the Status column only informs about the time since the last failing or successful request.

**Comment by sandrotosi** [comment]
please check https://github.com/CorralPeltzer/newTrackon/issues/64 - for example right now, calling https://newtrackon.com/api/stable `udp://tracker.tiny-vps.com:6969/announce` is at the top, with `udp://thetracker.org:80/announce` is in second position, but on https://newtrackon.com/ `udp://tracker.tiny-vps.com:6969/announce` status is "Working for 27 days" and `udp://thetracker.org:80/announce` status is "Working for 1 month"

so clearly the sort is not accurate and dont put the longest-working trackers at the top

**Comment by CorralPeltzer** [comment]
#64 is an unrelated front end bug that will be fixed.

Sorry for not being clear enough. Ordering of the trackers in the main table and the API endpoints happens first by **Uptime**, 2nd column starting from the left, which is just a percentage. When uptime is the same, **Added** is used, last column the main table.

The column you are referring to, **Status**, the 3rd column starting from the left, is completely ignored for default ordering, for the reasons stated in my previous comment.

**Comment by sandrotosi** [comment]
you are practically treating a tracker that's been up since 2 days and one since 2 months the  same, because they have 100% uptime. i think there should be a way to get a list of the trackers that didnt have any missed request for the longest time.

alternatively, why dont you just expose the very same information of the homepage via API, and let the clients do the sorting they prefer?
