### ISSUE TITLE
Trackers with Directory are Parsed as Just the Domain

### ISSUE THREAD

**Issue by leoherzog** [CorralPeltzer/newTrackon#81]
If you submit, for example, `https://ashrise.com:443/phoenix/announce`, it gets processed as `http://ashrise.com:443/announce`, `https://ashrise.com:443/announce`, and `udp://ashrise.com:443/announce`.

**Comment by CorralPeltzer** [comment]
This is intentional. To make clear to the users that they are actually trackers and not any random URLs, all submitted trackers are unified to `protocol://hostname:port/announce`.

For UDP trackers, the path is unnecessary but makes the URL more recognizable as a tracker. For HTTP(S) trackers, the path matters, with the [BEP48](https://www.bittorrent.org/beps/bep_0048.html) speficying that the strings `announce` or `scrape` must be in the path.

Although it is not stated they should be the _whole_ path, according to the spec, `http://example.com:80/any/random/announceStrange/path/` would be a valid tracker. Most of the trackers are just `/announce`, so this would increase confusion for non technical users on whether it's a public tracker or a normal website.

Also, public trackers usually receive tens of millions of requests a day, so it not a good idea to host other services under the same URL or even hostname. I have received multiple petitions to remove/change the hostname from people that did that and regretted after seeing the volume of requests. That's why newTrackon is more strict than the BitTorrent specification and limits the path to only `/announce`.

If you have a valid technical reason to have a different path other than just `/announce`, I'm open to talk about it.

**Comment by leoherzog** [comment]
Thanks for the reply. I hear you in regards to the spec, and you're right that most don't use a subdirectory. It's also worth noting that ashrise is one of the most popular trackers out there. `https://ashrise.com:443/phoenix/announce` is correct, `https://ashrise.com:443/announce` 404s. Another example I can think of is `http://linuxtracker.org:2710/00000000000000000000000000000000/announce`.
